name: ItemEditor
version: '1'
main: jcn.itemeditor.ItemEditor
api-version: '1.20'
commands:
  rename:
    description: Переименовать предмет
    usage: /rename Название предмета
    permission:  rename.perm
  relore:
    description: Основная команда
    usage: /relore Описание предмета
    permission: relore.perm